defaults:
  - _self_
  - environment: rccar
  - override /environment/train_car_params: car_2_blend
  - override /environment/eval_car_params: car_2_blend

hydra:
  run:
    dir: ${log_dir}/check-rccar/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/${hydra.job.name}
    subdir: ${hydra.job.override_dirname}/seed=${training.seed}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir
          - training.seed
          - wandb
    chdir: true

log_dir: outputs
baseline_trajectory: /home/anon/ethz/rl/safe-sim2real/data/baseline.pkl
check_trajectory: /home/anon/ethz/rl/safe-sim2real/data/trajectory-0.pkl
action_repeat: 1
episode_length: ???
decode_check: true
